IF EXISTS (SELECT name FROM sys.databases WHERE name = 'RetailStoreDB')
BEGIN
	ALTER DATABASE RetailStoreDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE RetailStoreDB;
END
GO

CREATE DATABASE RetailStoreDB;
GO

USE RetailStoreDB;
GO

CREATE TABLE Categories(
	CategoryID INT PRIMARY KEY IDENTITY(1,1),
    CategoryName VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Products(
	ProductID INT PRIMARY KEY IDENTITY(1,1),
	ProductName NVARCHAR(255) NOT NULL,
	CategoryID INT ,
	Price DECIMAL(10,2) NOT NULL CHECK(Price > 0),
	StockQuantity INT DEFAULT 0 CHECK(StockQuantity >= 0),
	CONSTRAINT FK_Category FOREIGN KEY (CategoryID)
		REFERENCES Categories(CategoryID) ON DELETE SET NULL
);

CREATE TABLE Customers(
	CustomerID INT PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(150) UNIQUE NOT NULL,
	RegistrationDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE Orders(
	OrderID INT PRIMARY KEY IDENTITY(1,1),
	CustomerID INT,
	OrderDate DATETIME DEFAULT GETDATE(),
	TotalAmount DECIMAL(10,2) DEFAULT 0,
	CONSTRAINT FK_Customer FOREIGN KEY (CustomerID)
		REFERENCES Customers(CustomerID) ON DELETE CASCADE
);


CREATE TABLE OrderDetails(
	OrderDetailID INT PRIMARY KEY IDENTITY(1,1),
    OrderID INT,
    ProductID INT,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    UnitPrice DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);


